- name: install filebeat
  apt:
    deb: 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ filebeat_version }}-amd64.deb'

- name: configure filebeat.yml
  template:
    src: 'filebeat.yml.j2'
    dest: '/etc/filebeat/filebeat.yml'
  notify:
    - restart filebeat

- name: start filebeat
  service:
    name: filebeat
    state: started

- name: enable filebeat
  service:
    name: filebeat
    enabled: yes
