---
- name: collect related component facts
  hosts: db
  tasks: []

- name: configure web
  hosts: web
  vars:
    loggly_for_nginx: yes

    # For live servers
    letsencrypt_cert_domains:
      - '{{ app_domain }}'
      - 'www.{{ app_domain }}'

    nginx_sites: '{{ app_web_nginx_sites }}'

    php_version: '7.2'
    php_packages_extra:
      - 'php{{ php_version }}-mysql'
    php_upload_max_filesize: '150M'
    php_post_max_size: '200M'
    php_enable_webserver: no
    php_enable_php_fpm: yes
    php_fpm_listen: '/var/run/php/php{{ php_version }}-fpm.sock'

    phpapp_project_name: '{{ project_full_name }}'
    phpapp_app_name: '{{ app_name }}'
    phpapp_source: '{{ app_source }}'
    phpapp_git_repo: '{{ app_git_repo }}'
    phpapp_version: '{{ app_version }}'
    phpapp_conf_env: '{{ app_conf_env }}'
  roles:
    - { role: sudo, tags: [ server ] }
    - { role: locales, tags: [ server ] }
    - { role: sshd, tags: [ server ] }
    - { role: fail2ban, tags: [ server ] }
    - { role: ntp, tags: [ server ] }

    - { role: newrelic-infrastructure, tags: [ monitoring ], when: is_live_env }
    - { role: loggly, tags: [ monitoring ], when: is_live_env }

    - { role: git, tags: [ app ] }
    - { role: letsencrypt, tags: [ app ], when: is_live_env and app_web_use_ssl }
    - { role: nginx, tags: [ app,nginx ] }
    - { role: php-versions, tags: [ app ] }
    - { role: php, tags: [ app ] }
    - { role: composer, tags: [ app ] }
    - { role: phpapp, tags: [ app,deploy ] }
