- name: Add PreserveFQDN to rsyslog.conf
  lineinfile:
    path: '/etc/rsyslog.conf'
    line: $PreserveFQDN on
    regexp: \$PreserveFQDN
    insertbefore: BOF
    state: present
  when: not is_docker
