version: "3.9"

services:

  amqp:
    build: apps/api
    container_name: lb_amqp

  db:
    build: apps/api
    container_name: lb_db
    entrypoint: bash /entrypoints/always.sh /entrypoints/db.sh
    ports:
      - "5432:5432"

  redis:
    build: apps/api
    container_name: lb_redis
    entrypoint: bash /entrypoints/always.sh /entrypoints/redis.sh

  web:
    build: apps/api
    container_name: lb_web
    entrypoint: bash /entrypoints/always.sh /entrypoints/web.sh
    ports:
      - "8000:8000"
    volumes:
      - ../lb-django:/src
