# Server
- name: locales
  src: oefenweb.locales
  version: v1.0.49

- name: ntp
  src: geerlingguy.ntp
  version: 2.3.0

- name: sshd
  src: silverlogic.sshd
  version: 0.6

- name: swapfile
  src: oefenweb.swapfile
  version: v2.0.34

# Monitoring
- name: newrelic-infrastructure
  src: newrelic.newrelic-infra
  version: 0.10.3

# Languages
- name: java
  src: william-yeh.oracle_java
  version: 2.11.0

- name: java-openjdk
  src: geerlingguy.java
  version: 1.10.0

- name: nodejs
  src: geerlingguy.nodejs
  version: 6.0.0

- name: php
  src: geerlingguy.php
  version: 4.7.0

- name: php-versions
  src: geerlingguy.php-versions
  version: 5.0.0

- name: rvm_ruby
  src: silverlogic.rvm
  version: v2.2.0

# Services
- name: mysql
  src: geerlingguy.mysql
  version: 3.3.2

- name: elasticsearch
  src: elastic.elasticsearch
  version: v7.15.1

- name: redis
  src: DavidWittman.redis
  version: 1.2.8

- name: rabbitmq
  src: silverlogic.rabbitmq
  version: 1.4.4

- name: nginx
  src: jdauphant.nginx
  version: v2.21.2

- name: postgresql
  src: silverlogic.postgresql
  version: v1.13.0

# Misc
- name: composer
  src: geerlingguy.composer
  version: 1.9.0

- name: letsencrypt
  src: https://github.com/thefinn93/ansible-letsencrypt
  version: cfc0b938dc2c9a8985be30a2f9ece8f4df0dd6fe

- name: certbot
  src: silverlogic.certbot
  version: 3.1.0

- src: geerlingguy.daemonize
  version: 1.2.2

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.2.0

- name: google-chrome
  src: mlangry.google-chrome
  version: 43198de46ef8fe4fde5d5a66a137e8fd421a9db2
