# Server
- name: locales
  src: oefenweb.locales
  version: v1.0.21

- name: ntp
  src: geerlingguy.ntp
  version: 1.6.0

- name: sshd
  src: silverlogic.sshd
  version: 0.6

- name: swapfile
  src: https://github.com/Oefenweb/ansible-swapfile
  version: 175ddb02972977d0341851c4f93170d00374998a

# Monitoring
- name: newrelic-infrastructure
  src: newrelic.newrelic-infra
  version: 0.4.0

# Languages
- name: java
  src: william-yeh.oracle_java
  version: 2.11.0

- name: java-openjdk
  src: geerlingguy.java
  version: 1.8.1

- name: nodejs
  src: geerlingguy.nodejs
  version: 4.2.0

- name: php
  src: geerlingguy.php
  version: 3.6.0

- name: php-versions
  src: geerlingguy.php-versions
  version: 2.1.3

- name: rvm_ruby
  src: silverlogic.rvm
  version: v2.2.0

# Services
- name: mysql
  src: geerlingguy.mysql
  version: 2.9.0

- name: elasticsearch
  src: https://github.com/elastic/ansible-elasticsearch
  version: 362156147300a7e8ada558f30b04df81ee440709

- name: redis
  src: DavidWittman.redis
  version: 1.2.4

- name: rabbitmq
  src: silverlogic.rabbitmq
  version: 1.4.3

- name: nginx
  src: jdauphant.nginx
  version: v2.18.1

- name: postgresql
  src: ANXS.postgresql
  version: v1.10.1

# Misc
- name: composer
  src: geerlingguy.composer
  version: 1.6.1

- name: letsencrypt
  src: https://github.com/thefinn93/ansible-letsencrypt
  version: cfc0b938dc2c9a8985be30a2f9ece8f4df0dd6fe

- name: certbot
  src: silverlogic.certbot
  version: 3.1.0

- src: geerlingguy.daemonize
  version: 1.1.1

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.1.1
