# Server
- name: locales
  src: tersmitten.locales
  version: v1.0.7

- name: ntp
  src: geerlingguy.ntp
  version: 1.4.0

- name: sshd
  src: willshersystems.sshd
  version: 0.5.1

- name: swapfile
  src: https://github.com/Oefenweb/ansible-swapfile
  version: 175ddb02972977d0341851c4f93170d00374998a

# Monitoring
- name: newrelic-infrastructure
  src: https://github.com/silverlogic/infrastructure-agent-ansible.git
  version: 0319bf594347367861c068ec18b0433c22a3fe6f

# Languages
- name: java
  src: williamyeh.oracle-java
  version: 2.11.0

- name: nodejs
  src: geerlingguy.nodejs
  version: 4.0.0

- name: php
  src: geerlingguy.php
  version: 3.4.5

# Services
- name: mysql
  src: geerlingguy.mysql
  version: 2.8.0

- name: elasticsearch
  src: https://github.com/elastic/ansible-elasticsearch
  version: 362156147300a7e8ada558f30b04df81ee440709

- name: redis
  src: DavidWittman.redis
  version: 1.2.4

- name: rabbitmq
  src: silverlogic.playbook-rabbitmq
  version: 1.4.1

- name: nginx
  src: jdauphant.nginx
  version: v2.9

- name: postgresql
  src: ANXS.postgresql
  version: v1.9.0

# Misc
- name: composer
  src: geerlingguy.composer
  version: 1.6.1

- name: letsencrypt
  src: https://github.com/thefinn93/ansible-letsencrypt
  version: cfc0b938dc2c9a8985be30a2f9ece8f4df0dd6fe

- src: geerlingguy.daemonize
  version: 1.1.1

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.1.1
