---
# App
app_name: 'web'
app_user: '{{ app_name }}'
app_repo: 'git@bitbucket.org:silverlogic/lb-nextjs.git'
app_domain: '{{ web_domain }}'
app_use_ssl: true
app_url: '{{ app_use_ssl | ternary("https", "http") }}://{{ app_domain }}'

# Nodeapp
app_nodejs_version: '12.x'
app_conf_env:
  appBaseURL: '{{ app_url }}'
  apiBaseURL: 'https://api.littlebirds.me/v1'
  NEXT_PUBLIC_API_BASE_URL: 'https://api.littlebirds.me/v1'
  apiDateFormat: 'YYYY-MM-DD'
  apiPageSize: 30
  fbAppId: '{{ app_facebook_app_id }}'
  sentry:
    DSN: '{{ app_sentry_dsn }}'
    publicDSN: '{{ app_sentry_public_dsn }}'
    environment: '{{ env }}'
    autoBreadcrumbs: true
    release: '{{ nodeapp_git_revision.after | default(nextjs_git_revision.after) }}'
  website:
    title: '{{ project_verbose_name }}'
    automaticAccountAgreement: true
    socialLogins: true

# Nginx
app_nginx_sites:
  app:
    template: 'nginx/web.conf.j2'
