---
- name: create wordpress group
  group:
    name: '{{ wordpress_group }}'
    state: 'present'

- name: create wordpress user
  user:
    name: '{{ wordpress_user }}'
    group: '{{ wordpress_group }}'
    home: '{{ wordpress_home }}'
    state: 'present'
  when: wordpress_user != 'vagrant'

- name: ensure home directory permissions
  file:
    path: '{{ wordpress_home }}'
    owner: '{{ wordpress_user }}'
    group: '{{ wordpress_group }}'
    state: 'directory'

- block:
  - name: get ssh key
    copy:
      src: '{{ wordpress_ssh_key_src }}'
      dest: '{{ wordpress_ssh_key }}'
      mode: 0600
    when: wordpress_use_git_clone

  - name: clone wordpress repo
    git:
      repo: '{{ wordpress_repo }}'
      version: '{{ wordpress_branch }}'
      dest: '{{ wordpress_dest }}'
      key_file: '{{ wordpress_ssh_key }}'
      accept_hostkey: yes
      force: yes
      ssh_opts: '-o ServerAliveInterval=600 -o TCPKeepAlive=yes -o IPQoS=cs0'
    when: wordpress_use_git_clone

  - name: ensure uploads is writable by group
    file:
      path: '{{ wordpress_dest }}/web/app/uploads'
      state: 'directory'
      recurse: no
      mode: 'g+w'

  - name: create .env file
    template:
      src: 'env.j2'
      dest: '{{ wordpress_dest }}/.env'

  - name: composer install
    composer:
      command: 'install'
      working_dir: '{{ wordpress_dest }}'

  - name: install wordpress
    command: wp core install
             --url="{{ wordpress_homeurl }}"
             --title="{{ wordpress_site_title }}"
             --admin_user="{{ wordpress_admin_user }}"
             --admin_password="{{ wordpress_admin_password }}"
             --admin_email="{{ wordpress_admin_email }}"
    args:
      chdir: "{{ wordpress_dest }}"
    register: wp_install_results
    changed_when: "'WordPress is already installed.' not in wp_install_results.stdout"
  become: yes
  become_user: '{{ wordpress_user }}'
