---
galaxy_info:
  role_name: rabbitmq
  author: Mayeu
  description: RabbitMQ is a complete and highly reliable enterprise messaging system based on the emerging AMQP standard.
  license: BSD
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - wheezy
    - jessie
    - stretch
  categories:
    - networking
dependencies: []
