---
- name: deploy web
  hosts: web
  vars:
    loggly_for_nginx: yes

    certbot_certs:
      - domains:
        - '{{ app_domain }}'

    nginx_sites: '{{ app_nginx_sites }}'

    middleman_user: '{{ app_user }}'
    middleman_repo: '{{ app_repo }}'
    middleman_branch: '{{ app_version }}'
    middleman_use_git_clone: '{{ is_live_env }}'
    middleman_rel_path: '/apidocs/'
  roles:
    - { role: server-common, tags: [ server ] }
    - { role: monitoring-common, tags: [ monitoring ] }

    - { role: git, tags: [ app ] }
    - { role: certbot, tags: [ app,certbot ], when: is_live_env and app_use_ssl }
    - { role: nginx, tags: [ app,nginx ] }
    - { role: middleman, tags: [ app,deploy ] }
