- name: install required packages
  apt: name={{ packages }} state=present update_cache=yes cache_valid_time=6000
  vars:
    packages:
      - build-essential
      - libbz2-dev
      - libdb5.3-dev
      - libexpat1-dev
      - libgdbm-dev
      - liblzma-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline6-dev
      - libsqlite3-dev
      - libssl-dev
      - libffi-dev
      - python-setuptools
      - zlib1g-dev
