- name: install required packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=6000
  with_items:
    - build-essential
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline6-dev
    - libdb5.3-dev
    - libgdbm-dev
    - libsqlite3-dev
    - libssl-dev
    - libbz2-dev
    - libexpat1-dev
    - liblzma-dev
    - zlib1g-dev
