- name: install required packages
  yum: name={{ item }} state=present
  with_items:
    - '@development tools'
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - tk-devel
    - gdbm-devel
    - db4-devel
    - libpcap-devel
    - xz-devel
    - expat-devel
    - wget
