---
- include_tasks: 'install-{{ ansible_os_family }}.yml'

- name: download and extract python source
  unarchive: >
    src={{ python_source_url }}
    copy=no
    dest={{ python_source_dest }}

- name: compile and install
  shell: '{{ item }}'
  args:
    chdir: '{{ python_source_dir }}'
  with_items:
    - './configure --enable-shared --prefix={{ python_prefix }}'
    - 'make'
    - 'make install'

- name: delete source files
  file: path={{ python_source_dir }} state=absent

- name: normalize python exec name
  shell: 'mv python? python || true'
  args:
    chdir: '{{ python_prefix }}/bin'

- name: normalize pip exec name
  shell: 'mv pip? pip || true'
  args:
    chdir: '{{ python_prefix }}/bin'

- name: add python to ld configs
  template:
    src: 'ld.conf.j2'
    dest: '/etc/ld.so.conf.d/python.conf'

- name: update ldconfig cache
  shell: 'ldconfig'
