---
- name: install packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time={{ 60*60*24 }}
  with_items:
    - 'libjpeg-dev'
    - 'libpq-dev'
    - 'gdal-bin'

- name: create celery group
  group:
    name: '{{ celery_group }}'
    state: 'present'

- name: create celery user
  user:
    name: '{{ celery_user }}'
    group: '{{ celery_group }}'
    home: '{{ celery_home }}'
    state: 'present'

- name: ensure home directory permissions
  file:
    path: '{{ celery_home }}'
    owner: '{{ celery_user }}'
    group: '{{ celery_group }}'
    state: 'directory'

- block:
  - name: get ssh key
    copy:
      src: '{{ celery_ssh_key_src }}'
      dest: '{{ celery_ssh_key }}'
      mode: 0600
    when: celery_use_git_clone

  - name: run pre-clone hook
    include_tasks: '{{ celery_pre_clone_hook }}'
    when: celery_pre_clone_hook != ''

  - name: clone celery repo
    git:
      repo: '{{ celery_repo }}'
      version: '{{ celery_branch }}'
      dest: '{{ celery_dest }}'
      key_file: '{{ celery_ssh_key }}'
      accept_hostkey: yes
      force: yes
    notify:
      - restart celery
    when: celery_use_git_clone

  - name: run post-clone hook
    include_tasks: '{{ celery_post_clone_hook }}'
    when: celery_post_clone_hook != ''

  - name: create virtualenv
    pip:
      virtualenv: '{{ celery_virtualenv }}'
      virtualenv_command: '{{ celery_virtualenv_command }}'
      virtualenv_python: '{{ celery_python }}'
      requirements: '{{ celery_dest }}/{{ celery_requirements_txt }}'
      chdir: '{{ celery_dest }}'
    notify:
      - restart celery

  - name: run post-virtualenv hook
    include_tasks: '{{ celery_post_virtualenv_hook }}'
    when: celery_post_virtualenv_hook != ''

  become: yes
  become_user: '{{ celery_user }}'

- name: create celery service file
  template:
    src: 'celery.service.j2'
    dest: '{{ celery_service_file }}'
    mode: 0644
  notify:
    - restart celery

- name: create config directory
  file:
    path: '{{ celery_service_env_file|dirname }}'
    state: 'directory'

- name: create celery service environment file
  template:
    src: 'celery.service.env.j2'
    dest: '{{ celery_service_env_file }}'
    mode: 0644
  notify:
    - restart celery

- name: ensure service files are up to date
  shell: systemctl daemon-reload

- name: ensure celery service is started & enabled
  service: name={{ celery_service }} state=started enabled=yes
