---
component_name: 'db'

postgresql_version: '9.6'
postgresql_ext_postgis_version: '2.3'
postgresql_log_destination: 'syslog'
postgresql_log_checkpoints: yes
postgresql_log_connections: yes
postgresql_log_disconnections: yes
postgresql_log_duration: no
postgresql_log_statement:  'mod'
postgresql_log_min_duration_statement: 250
postgresql_syslog_split_messages: no
