---
- name: configure web
  hosts: web
  vars:
    loggly_for_nginx: yes

    # For live servers
    letsencrypt_cert_domains:
      - '{{ app_domain }}'
      - 'www.{{ app_domain }}'

    nginx_sites: '{{ app_nginx_sites }}'

    nodejs_version: '{{ app_nodejs_version }}'
    nodeapp_user: '{{ app_user }}'
    nodeapp_use_git_clone: '{{ is_live_env }}'
    nodeapp_repo: '{{ app_repo }}'
    nodeapp_branch: '{{ app_version }}'
    nodeapp_package_manager: 'yarn'
    nodeapp_conf_env: '{{ app_conf_env }}'
  roles:
    - { role: server-common, tags: [ server ] }
    - { role: monitoring-common, tags: [ monitoring ] }

    - { role: swapfile, swapfile_size: 1G, tags: [ server ] }

    - { role: git, tags: [ app ] }
    - { role: letsencrypt, tags: [ app ], when: is_live_env and app_use_ssl }
    - { role: nginx, tags: [ app,nginx ] }
    - { role: nodejs, tags: [ app ] }
    - { role: nodeapp, tags: [ app,deploy ] }
