---
- name: collect related component facts
  hosts: db
  tasks: []

- name: deploy web
  hosts: web
  vars:
    loggly_for_nginx: yes

    letsencrypt_cert_domains:
      - '{{ app_domain }}'

    ssmtp_hostname: 'noreply@{{ app_domain }}'
    ssmtp_mailhub: '{{ app_email_host }}:{{ app_email_port }}'
    ssmtp_user: '{{ app_email_username }}'
    ssmtp_password: '{{ app_email_password }}'
    ssmtp_tls: '{{ app_email_use_tls | ternary("Yes", "No") }}'
    ssmtp_start_tls: '{{ app_email_use_tls | ternary("Yes", "No") }}'

    nginx_sites: '{{ app_web_nginx_sites }}'

    php_packages:
      - php5-cli
      - php5-common
      - php5-curl
      - php5-dev
      - php5-fpm
      - php5-gd
      - php5-mcrypt
      - php5-mysql
      - php5-xmlrpc
    php_enable_webserver: no
    php_enable_php_fpm: yes
    php_fpm_daemon: php5-fpm
    php_fpm_listen: '/var/run/php5-fpm.sock'
    php_fpm_conf_path: "/etc/php5/fpm"
    php_sendmail_path: '/usr/sbin/ssmtp -t'

    wordpress_user: '{{ app_user }}'
    wordpress_repo: '{{ app_repo }}'
    wordpress_branch: '{{ app_version }}'
    wordpress_use_git_clone: '{{ is_live_env }}'
    wordpress_site_title: '{{ app_site_title }}'
    wordpress_admin_user: '{{ app_admin_user }}'
    wordpress_admin_password: '{{ app_admin_password }}'
    wordpress_admin_email: '{{ app_admin_email }}'
    wordpress_db_name: '{{ app_db_name }}'
    wordpress_db_user: '{{ app_db_user }}'
    wordpress_db_password: '{{ app_db_password }}'
    wordpress_db_host: '{{ app_db_host }}'
    wordpress_env: '{{ app_env }}'
    wordpress_homeurl: '{{ app_homeurl }}'
    wordpress_auth_key: '{{ app_auth_key }}'
    wordpress_secure_auth_key: '{{ app_secure_auth_key }}'
    wordpress_logged_in_key: '{{ app_logged_in_key }}'
    wordpress_nonce_key: '{{ app_nonce_key }}'
    wordpress_auth_salt: '{{ app_auth_salt }}'
    wordpress_secure_auth_salt: '{{ app_secure_auth_salt }}'
    wordpress_logged_in_salt: '{{ app_logged_in_salt }}'
    wordpress_nonce_salt: '{{ app_nonce_salt }}'
  roles:
    - { role: server-common, tags: [ server ] }
    - { role: monitoring-common, tags: [ monitoring ] }

    - { role: git, tags: [ app ] }
    - { role: letsencrypt, tags: [ app ], when: is_live_env and app_use_ssl }
    - { role: ssmtp, tags: [ app ] }
    - { role: nginx, tags: [ app,nginx ] }
    - { role: php, tags: [ app ] }
    - { role: composer, tags: [ app ] }
    - { role: wp-cli, tags: [ app ] }
    - { role: wordpress, tags: [ app, deploy ] }
