---
- name: configure database
  hosts: db
  vars:
    postgresql_ext_install_contrib: yes
    postgresql_databases:
      - name: '{{ app_db_name }}'
    postgresql_database_extensions:
      - db: 'template1'
        extensions:
          - citext
      - db: '{{ app_db_name }}'
        extensions:
          - citext
    postgresql_users:
      - name: '{{ app_db_name }}'
        pass: '{{ app_db_password }}'
    postgresql_user_privileges:
      - name: '{{ app_db_user }}'
        db: '{{ app_db_name }}'
        priv: ALL
        role_attr_flags: 'SUPERUSER'
    postgresql_listen_addresses:
      - localhost
      - '{{ private_interface.ipv4.address }}'
    postgresql_pg_hba_passwd_hosts:
      - '0.0.0.0/0'
  roles:
    - { role: server-common, tags: [ server ] }
    - { role: monitoring-common, tags: [ monitoring ] }

    - { role: postgresql, tags: [ app ] }

