---
- import_playbook: 'config_db.yml'
- import_playbook: 'config_redis.yml'
- import_playbook: 'config_amqp.yml'
- import_playbook: 'config_load_balancer.yml'
- import_playbook: 'config_web.yml'
- import_playbook: 'config_worker.yml'
- import_playbook: 'config_worker_monitor.yml'
- import_playbook: 'config_scheduler.yml'
