---
- name: collect related component facts
  hosts: web
  tasks: []

- name: configure load balancer
  hosts: load-balancer
  vars:
    loggly_for_nginx: yes
    certbot_certs:
      - domains:
        - '{{ app_domain }}'
    nginx_sites: '{{ app_load_balancer_nginx_sites }}'
    django_websocket: '{{ app_django_websocket }}'
  roles:
    - { role: server-common, tags: [ server ] }
    - { role: monitoring-common, tags: [ monitoring ] }

    - { role: certbot, tags: [ app,certbot ], when: is_live_env }
    - { role: nginx, tags: [ app,nginx ] }
