---
- name: configure database
  hosts: db
  vars:
    postgresql_ext_install_contrib: yes
    postgresql_databases:
      - name: '{{ app_db_name }}'
    postgresql_database_extensions:
      - db: 'template1'
        extensions:
          - citext
      - db: '{{ app_db_name }}'
        extensions:
          - citext
    postgresql_users:
      - name: '{{ app_db_name }}'
        pass: '{{ app_db_password }}'
    postgresql_user_privileges:
      - name: '{{ app_db_user }}'
        db: '{{ app_db_name }}'
        priv: ALL
        role_attr_flags: 'SUPERUSER'
    postgresql_listen_addresses:
      - localhost
      - '{{ ansible_eth1.ipv4.address }}'
    postgresql_pg_hba_passwd_hosts:
      - '0.0.0.0/0'
  roles:
    - { role: sudo, tags: [ server ] }
    - { role: locales, tags: [ server ] }
    - { role: sshd, tags: [ server ] }
    - { role: fail2ban, tags: [ server ] }
    - { role: ntp, tags: [ server ] }

    - { role: newrelic-infrastructure, tags: [ monitoring ], when: is_live_env }
    - { role: loggly, tags: [ monitoring ], when: is_live_env }

    - { role: postgresql, tags: [ app ] }

