---
- name: collect related component facts
  hosts: db:amqp
  tasks: []

- name: configure scheduler
  hosts: scheduler
  vars:
    celery_beat_user: '{{ app_user }}'
    celery_beat_repo: '{{ app_repo }}'
    celery_beat_branch: '{{ app_version }}'
    celery_beat_use_git_clone: '{{ is_live_env }}'
    celery_beat_requirements_txt: '{{ app_django_requirements_txt }}'
    celery_beat_conf_env: '{{ app_scheduler_conf_env }}'
  roles:
    - { role: server-common, tags: [ server ] }
    - { role: monitoring-common, tags: [ monitoring ] }

    - { role: swapfile, swapfile_size: 1G, tags: [server] }

    - { role: git, tags: [ app ] }
    - { role: python, tags: [ app,deploy ] }
    - { role: celery-beat, tags: [ app,deploy ] }
